export interface IProject {
  id: number;
  userId: number;
  name: string;
  description: string;
  about: string;
  isPublic: boolean;
}

export const rawProjectItems: IProject[] = [
  {
    id: 1,
    userId: 1,
    name: "Project 1",
    description: "Description for Project 1",
    about: "Microelectronics project related to semiconductor materials.",
    isPublic: true,
  },
  {
    id: 2,
    userId: 2,
    name: "Project 2",
    description: "Description for Project 2",
    about: "Semiconductor research project focused on optimization.",
    isPublic: true,
  },
  {
    id: 3,
    userId: 3,
    name: "Project 3",
    description: "Description for Project 3",
    about: "Semiconductor device modeling and simulation project.",
    isPublic: false,
  },
  {
    id: 4,
    userId: 4,
    name: "Project 4",
    description: "Description for Project 4",
    about: "Microelectronics project exploring advanced materials.",
    isPublic: true,
  },
  {
    id: 5,
    userId: 5,
    name: "Project 5",
    description: "Description for Project 5",
    about: "Semiconductor manufacturing process optimization project.",
    isPublic: false,
  },
  {
    id: 6,
    userId: 6,
    name: "Project 6",
    description: "Description for Project 6",
    about: "Microelectronics project for low-power semiconductor devices.",
    isPublic: true,
  },
  {
    id: 7,
    userId: 7,
    name: "Project 7",
    description: "Description for Project 7",
    about: "Semiconductor data analysis and modeling project.",
    isPublic: true,
  },
  {
    id: 8,
    userId: 8,
    name: "Project 8",
    description: "Description for Project 8",
    about: "Semiconductor equipment control app development project.",
    isPublic: false,
  },
  {
    id: 9,
    userId: 9,
    name: "Project 9",
    description: "Description for Project 9",
    about:
      "Microelectronics project for semiconductor fabrication workflow automation.",
    isPublic: true,
  },
  {
    id: 10,
    userId: 10,
    name: "Project 10",
    description: "Description for Project 10",
    about: "Web design project for semiconductor-related websites.",
    isPublic: true,
  },
  {
    id: 11,
    userId: 11,
    name: "Project 11",
    description: "Description for Project 11",
    about: "Semiconductor automation and control systems project.",
    isPublic: false,
  },
  {
    id: 12,
    userId: 12,
    name: "Project 12",
    description: "Description for Project 12",
    about: "User interface design for semiconductor tools project.",
    isPublic: true,
  },
  {
    id: 13,
    userId: 13,
    name: "Project 13",
    description: "Description for Project 13",
    about: "Quantum computing research in semiconductor materials project.",
    isPublic: false,
  },
  {
    id: 14,
    userId: 14,
    name: "Project 14",
    description: "Description for Project 14",
    about: "App development for semiconductor device monitoring project.",
    isPublic: true,
  },
  {
    id: 15,
    userId: 15,
    name: "Project 15",
    description: "Description for Project 15",
    about: "Yield analysis and optimization in semiconductor project.",
    isPublic: false,
  },
  {
    id: 16,
    userId: 16,
    name: "Project 16",
    description: "Description for Project 16",
    about:
      "Intuitive UI/UX design for semiconductor equipment control project.",
    isPublic: true,
  },
  {
    id: 17,
    userId: 17,
    name: "Project 17",
    description: "Description for Project 17",
    about: "Semiconductor manufacturing process optimization project.",
    isPublic: true,
  },
  {
    id: 18,
    userId: 18,
    name: "Project 18",
    description: "Description for Project 18",
    about: "Semiconductor fabrication workflow automation project.",
    isPublic: false,
  },
  {
    id: 19,
    userId: 19,
    name: "Project 19",
    description: "Description for Project 19",
    about: "Open-source semiconductor simulation projects.",
    isPublic: true,
  },
  {
    id: 20,
    userId: 20,
    name: "Project 20",
    description: "Description for Project 20",
    about: "Creating visually stunning semiconductor-related websites project.",
    isPublic: true,
  },
  {
    id: 21,
    userId: 21,
    name: "Project 21",
    description: "Description for Project 21",
    about: "Database management in semiconductor project.",
    isPublic: false,
  },
  {
    id: 22,
    userId: 22,
    name: "Project 22",
    description: "Description for Project 22",
    about: "AI in semiconductor device modeling and simulation project.",
    isPublic: true,
  },
  {
    id: 23,
    userId: 23,
    name: "Project 23",
    description: "Description for Project 23",
    about: "Mobile app development for semiconductor-related apps project.",
    isPublic: true,
  },
  {
    id: 24,
    userId: 24,
    name: "Project 24",
    description: "Description for Project 24",
    about:
      "Leveraging data analysis for semiconductor process optimization project.",
    isPublic: false,
  },
  {
    id: 25,
    userId: 25,
    name: "Project 25",
    description: "Description for Project 25",
    about:
      "Creating responsive and accessible semiconductor-related websites project.",
    isPublic: true,
  },
  {
    id: 26,
    userId: 26,
    name: "Project 26",
    description: "Description for Project 26",
    about: "Building scalable and maintainable semiconductor systems project.",
    isPublic: true,
  },
  {
    id: 27,
    userId: 27,
    name: "Project 27",
    description: "Description for Project 27",
    about: "Elegant and user-centric semiconductor-related designs project.",
    isPublic: false,
  },
  {
    id: 28,
    userId: 28,
    name: "Project 28",
    description: "Description for Project 28",
    about: "JavaScript and modern semiconductor technologies project.",
    isPublic: true,
  },
  {
    id: 29,
    userId: 29,
    name: "Project 29",
    description: "Description for Project 29",
    about: "Cloud infrastructure for semiconductor companies project.",
    isPublic: true,
  },
  {
    id: 30,
    userId: 30,
    name: "Project 30",
    description: "Description for Project 30",
    about: "Responsive web design for semiconductor applications project.",
    isPublic: false,
  },
  {
    id: 31,
    userId: 31,
    name: "Project 31",
    description: "Description for Project 31",
    about: "Deep learning in semiconductor manufacturing project.",
    isPublic: true,
  },
  {
    id: 32,
    userId: 32,
    name: "Project 32",
    description: "Description for Project 32",
    about: "Cross-platform app development for semiconductor devices project.",
    isPublic: true,
  },
  {
    id: 33,
    userId: 33,
    name: "Project 33",
    description: "Description for Project 33",
    about: "Advanced semiconductor research project.",
    isPublic: false,
  },
  {
    id: 34,
    userId: 1,
    name: "Project 34",
    description: "Description for Project 34",
    about: "Microelectronics project related to semiconductor materials.",
    isPublic: true,
  },
  {
    id: 35,
    userId: 2,
    name: "Project 35",
    description: "Description for Project 35",
    about: "Semiconductor research project focused on optimization.",
    isPublic: true,
  },
  {
    id: 36,
    userId: 3,
    name: "Project 36",
    description: "Description for Project 36",
    about: "Semiconductor device modeling and simulation project.",
    isPublic: false,
  },
  {
    id: 37,
    userId: 4,
    name: "Project 37",
    description: "Description for Project 37",
    about: "Microelectronics project exploring advanced materials.",
    isPublic: true,
  },
  {
    id: 38,
    userId: 5,
    name: "Project 38",
    description: "Description for Project 38",
    about: "Semiconductor manufacturing process optimization project.",
    isPublic: false,
  },
  {
    id: 39,
    userId: 6,
    name: "Project 39",
    description: "Description for Project 39",
    about: "Microelectronics project for low-power semiconductor devices.",
    isPublic: true,
  },
  {
    id: 40,
    userId: 7,
    name: "Project 40",
    description: "Description for Project 40",
    about: "Semiconductor data analysis and modeling project.",
    isPublic: true,
  },
  {
    id: 41,
    userId: 8,
    name: "Project 41",
    description: "Description for Project 41",
    about: "Semiconductor equipment control app development project.",
    isPublic: false,
  },
  {
    id: 42,
    userId: 9,
    name: "Project 42",
    description: "Description for Project 42",
    about:
      "Microelectronics project for semiconductor fabrication workflow automation.",
    isPublic: true,
  },
  {
    id: 43,
    userId: 10,
    name: "Project 43",
    description: "Description for Project 43",
    about: "Web design project for semiconductor-related websites.",
    isPublic: true,
  },
  {
    id: 44,
    userId: 11,
    name: "Project 44",
    description: "Description for Project 44",
    about: "Semiconductor automation and control systems project.",
    isPublic: false,
  },
  {
    id: 45,
    userId: 12,
    name: "Project 45",
    description: "Description for Project 45",
    about: "User interface design for semiconductor tools project.",
    isPublic: true,
  },
  {
    id: 46,
    userId: 13,
    name: "Project 46",
    description: "Description for Project 46",
    about: "Quantum computing research in semiconductor materials project.",
    isPublic: false,
  },
  {
    id: 47,
    userId: 14,
    name: "Project 47",
    description: "Description for Project 47",
    about: "App development for semiconductor device monitoring project.",
    isPublic: true,
  },
  {
    id: 48,
    userId: 15,
    name: "Project 48",
    description: "Description for Project 48",
    about: "Yield analysis and optimization in semiconductor project.",
    isPublic: false,
  },
  {
    id: 49,
    userId: 16,
    name: "Project 49",
    description: "Description for Project 49",
    about:
      "Intuitive UI/UX design for semiconductor equipment control project.",
    isPublic: true,
  },
  {
    id: 50,
    userId: 17,
    name: "Project 50",
    description: "Description for Project 50",
    about: "Semiconductor manufacturing process optimization project.",
    isPublic: true,
  },
];
